docs: explain IndieAuth
Inklings-io/selfauth pull request #18
Opened 2017-07-09 11:27 UTC by sebsel

Some new docs about what Selfauth really is.

2017-07-09 17:16 UTC, Zegnat commented on README.md
> +- While Selfauth will work with old versions of PHP, the ability to get sufficiently random strings was not added until version 5.6. While older versions are not completely insecure, **it is strongly
It isn’t just random strings anymore, also things like `hash_equals`. And possibly the `password_`-functions if we end up using those.

Can we have a more general description that for PHP versions below 5.6 we can’t use PHP’s security features and that we cannot guarantee the same full security even though Selfauth will still be functional?

2017-07-09 17:16 UTC, Zegnat commented on README.md
> +- Currently selfauth only supports authentication, not authorization.  Meaning **scopes will not work yet**. If you need access to these features, it is advisable to use something else for now.
This isn’t strictly true. Selfauth will happily issue a code for authorisation use, with scopes included in the HMAC and code.

2017-07-09 18:00 UTC, sebsel commented on README.md
> +- While Selfauth will work with old versions of PHP, the ability to get sufficiently random strings was not added until version 5.6. While older versions are not completely insecure, **it is strongly
I made this "While Selfauth will work with old versions of PHP, some of the more secure functions Selfauth uses were not added until version 5.6." on my local copy now.

2017-07-09 18:35 UTC, sebsel commented on README.md
> +- Currently selfauth only supports authentication, not authorization.  Meaning **scopes will not work yet**. If you need access to these features, it is advisable to use something else for now.
At the moment, this is true. I created #19, and once that closes we can remove / change this warning.

2017-07-10 12:54 UTC, dissolve requested changes
One text change, the rest looks good to me

2017-07-10 12:54 UTC, dissolve commented on README.md
> +To test it, you can go to an App that supports IndieAuth and enter your personal URL. [IndieAuth.com](https://indieauth.com/) has a test-form on the frontpage. If you also link to your social media a
Last sentence here is really confusing.  Suggest splitting it to two sentences. 

IndieAuth.com might show you a list of buttons.  To use selfauth, click on the one that ...

2017-07-10 12:58 UTC, dissolve commented
Actually, this mentions that setup.php stops working, is that true yet?

2017-07-10 13:15 UTC, Zegnat commented
> Actually, this mentions that setup.php stops working, is that true yet?

I think this refers to the fact that setup.php will not create/overwrite config.php if it already exists.

2017-07-10 18:32 UTC, dissolve commented
its also moot as there is a PR for that now anyway :smile:

2017-07-10 19:41 UTC, dissolve approved these changes

2017-07-10 19:41 UTC, merged